from typing import Union

Numeric = list[Union[int, float]]

class Tensor:
    shape: list[int]
    ndim: int
    strides: list[int]
    data: list[float]
    size: int
    requires_grad: bool

    def __init__(self, data: Numeric, requires_grad: bool) -> None: ...
    def __add__(self, other: "Tensor") -> "Tensor": ...
    def __sub__(self, other: "Tensor") -> "Tensor": ...
    def __mul__(self, other: "Tensor") -> "Tensor": ...
    def __truediv__(self, other: "Tensor") -> "Tensor": ...
    def __matmul__(self, other: "Tensor") -> "Tensor": ...

    @property
    def T(self) -> "Tensor": ...

    @property
    def mT(self) -> "Tensor": ...

def tensor(data: Numeric, requires_grad: bool = False) -> Tensor: ...
